---
version: '3.8'

x-spt-common:
  &spt-common
  image: node:16.17.1-buster
  working_dir: /home/node
  user: node
  entrypoint: bash
  volumes:
    # files
    - ./.settings:/home/node/.settings
    - ./docker_compose_run_server.sh:/home/node/docker_compose_run_server.sh
    # folders
    - ./app:/home/node/app
    - ./app/src:/home/node/app/obj
    - ./node_modules:/home/node/app/node_modules
    - ./mods:/home/node/app/user/mods
    - ./profiles:/home/node/app/user/profiles

services:
  init:
    <<: *spt-common
    command:
      - -c
      - |
        echo
        echo "Init" 
        cd app
        yarn || exit
        echo "Finish init"

  run:
    <<: *spt-common
    command:
      - -c
      - |
        echo
        sh docker_compose_run_server.sh
    ports:
      - "6969:6969"
      - "6970:6970"
    healthcheck:
      test: curl --fail http://localhost:6969/healthcheck
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 60s
    restart: always
    labels:
      - "autoheal=true"
    depends_on:
      init:
        condition: service_completed_successfully

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      init:
        condition: service_completed_successfully
